<?php
$title = 'Contacts';
$this->headTitle($title);
?>
<strong>Module:</strong>        WiContact &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index

<h1><?php echo $this->escapehtml($title); ?></h1>

<a href="<?php echo $this->url('wi-contact', array('action'=>'add'));?>">Add new Contact</a>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
    
        <?php foreach ( $contacts as $contact ) :?>

            <tr>
                <td><?php echo $this->escapehtml($contact->getId()); ?></td>
                <td><?php echo $this->escapehtml($contact->getName()); ?></td>
                <td><a href="<?php echo $this->url('wi-contact', array('action'=>'view', 'id'=>$contact->getId())); ?>">View</a></td>
                <td><a href="<?php echo $this->url('wi-contact', array('action'=>'edit', 'id'=>$contact->getId())); ?>">Edit</a></td>
                <td><a href="<?php echo $this->url('wi-contact', array('action'=>'delete', 'id'=>$contact->getId())); ?>">Delete</a></td>
            </tr>
        
        <?php endforeach; ?>
        
    </tbody>
</table>