<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WiContacts\Module'                        => __DIR__ . '/Module.php',
    'WiContacts\Controller\IndexController' => __DIR__ . '/src/WiContacts/Controller/IndexController.php',
    'WiContactsTest\Framework\TestCase'        => __DIR__ . '/tests/WiContacts/Framework/TestCase.php',
    'WiContactsTest\SampleTest'                => __DIR__ . '/tests/WiContacts/SampleTest.php',
);
