<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CPIps\Module'                        => __DIR__ . '/Module.php',
    'CPIps\Controller\IndexController' => __DIR__ . '/src/CPIps/Controller/IndexController.php',
    'CPIpsTest\Framework\TestCase'        => __DIR__ . '/tests/CPIps/Framework/TestCase.php',
    'CPIpsTest\SampleTest'                => __DIR__ . '/tests/CPIps/SampleTest.php',
);
