<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WiBase\Module'                        => __DIR__ . '/Module.php',
    'WiBase\Controller\IndexController' => __DIR__ . '/src/WiBase/Controller/IndexController.php',
    'WiBaseTest\Framework\TestCase'        => __DIR__ . '/tests/WiBase/Framework/TestCase.php',
    'WiBaseTest\SampleTest'                => __DIR__ . '/tests/WiBase/SampleTest.php',
);
