<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WiContact\Module'                        => __DIR__ . '/Module.php',
    'WiContact\Controller\IndexController' => __DIR__ . '/src/WiContact/Controller/IndexController.php',
    'WiContactTest\Framework\TestCase'        => __DIR__ . '/tests/WiContact/Framework/TestCase.php',
    'WiContactTest\SampleTest'                => __DIR__ . '/tests/WiContact/SampleTest.php',
);
